---
# SPDX-FileCopyrightText: 2025 Pavel Dimov <@sagat79>
#
# SPDX-License-Identifier: CC0-1.0

- name: Setup Forgejo when enabled
  tags:
    - setup-all
    - setup-forgejo
    - install-all
    - install-forgejo
  block:
    - name: Validate Forgejo configuration
      when: forgejo_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Forgejo
      when: forgejo_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Uninstall Forgejo when disabled
  tags:
    - setup-all
    - setup-forgejo
  block:
    - name: Uninstall Forgejo
      when: not forgejo_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
